app:
  security:
    secret: Clickyman
    exprireIn: 3000
    jwtRefreshExpireTimeInMs: 5000
    encryptionKey: Clickyman1234567
    initVector: Clickyman1234567
spring:
  jpa:
    database: POSTGRESQL
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    username: postgres 
    password: root
    url: jdbc:postgresql://localhost:5432/postgres
    platform: postgres
    hikari:
      connection-timeout: 20000
      maximum-pool-size: 5
      
server:
  port: 8000
    